### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by triple111** [qrogers/pyscape#1]
I get an issue trying to run pyscape.py, doing an ls in the directory shows the file as being there.

Traceback (most recent call last):
  File "pyscape.py", line 8, in <module>
    from game_objects.units.player import Player
  File "/home/triple111/Downloads/pyscape-master/bin/game_objects/units/**init**.py", line 6, in <module>
    for file in os.listdir('/bin/game_objects/units'):
OSError: [Errno 2] No such file or directory: '/bin/game_objects/units'

**Comment by qrogers** [comment]
Try running start.py, it's one directory up.
